apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../app
  - frontend-http-public-route.yaml
  - frontend-https-public-route.yaml
  - namespace.yaml

namespace: prod
