apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: more-cars-frontend
          image: dennisgerike/more-cars-frontend:0.1.0
          resources:
            requests:
              cpu: "50m"
              memory: "210Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
