apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: more-cars-frontend
          image: docker.io/dennisgerike/more-cars-frontend:0.2.0
          #image: ghcr.io/more-cars/frontend:0.2.0
          env:
            - name: API_HOST
              value: $(API_SERVICE_SERVICE_HOST)
            - name: API_PORT
              value: $(API_SERVICE_SERVICE_PORT)
          resources:
            requests:
              cpu: "50m"
              memory: "210Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
