apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001
