export enum ModelNodeType {
    COMPANY = 'company',
    BRAND = 'brand',
    CAR_MODEL = 'car_model',
    CAR_MODEL_VARIANT = 'car_model_variant',
    PRICE = 'price',
    RACE_TRACK = 'race_track',
    TRACK_LAYOUT = 'track_layout',
    RACING_SERIES = 'racing_series',
    RACING_EVENT = 'racing_event',
    RACING_SESSION = 'racing_session',
    SESSION_RESULT = 'session_result',
    LAP_TIME = 'lap_time',
    RACING_GAME = 'racing_game',
    GAMING_PLATFORM = 'gaming_platform',
    MODEL_CAR = 'model_car',
    MODEL_CAR_BRAND = 'model_car_brand',
    MAGAZINE = 'magazine',
    MAGAZINE_ISSUE = 'magazine_issue',
    RATING = 'rating',
    PROGRAMME = 'programme',
    PROGRAMME_EPISODE = 'programme_episode',
    MOTOR_SHOW = 'motor_show',
    VIDEO = 'video',
    IMAGE = 'image',
}
