on:
  workflow_call:

jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run Integration Tests
        run: npm run tests:integration
