name: Run All Test Suites

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-typescript-code:
    uses: ./.github/workflows/lint-typescript-code.yml

  run-integration-tests:
    uses: ./.github/workflows/run-integration-tests.yml
